import Sidebar from './components/Sidebar'
import TopLoadingbar from './components/TopLoadingbar'
import Providers from './contexts/Providers'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'LUNU 🔥',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <TopLoadingbar/>
            <div className='flex'>
              <Sidebar />
              <div className="ml-[59px]">
                <Providers>
                  {children}
                </Providers>
              </div>
            </div>
      </body>
    </html>
  )
}
